// css/estilo.js
import { StyleSheet } from 'react-native';

const estilos = {
  estilosSplash: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#1a1a1a',
      justifyContent: 'center',
      alignItems: 'center',
    },
    logo: {
      width: 150,
      height: 150,
      borderRadius: 75,
      marginBottom: 20,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#FFD700',
      marginBottom: 10,
      textAlign: 'center',
    },
    spinner: {
      marginTop: 20,
    },
  }),

  estilosLogin: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#2a2a2a',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    title: {
      fontSize: 32,
      fontWeight: 'bold',
      color: '#FFD700',
      marginBottom: 40,
    },
    input: {
      width: '100%',
      backgroundColor: '#444',
      borderRadius: 8,
      padding: 15,
      marginBottom: 15,
      color: '#fff',
      fontSize: 16,
      borderWidth: 1,
      borderColor: '#FFD700',
    },
    button: {
      backgroundColor: '#FFD700',
      borderRadius: 8,
      paddingVertical: 15,
      paddingHorizontal: 30,
      marginTop: 20,
      width: '100%',
      alignItems: 'center',
    },
    buttonText: {
      color: '#000',
      fontSize: 18,
      fontWeight: 'bold',
    },
    errorText: {
      color: '#FF6347',
      marginTop: 10,
      textAlign: 'center',
    },
  }),

  estilosHome: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#2a2a2a',
    },
    header: {
      backgroundColor: '#FFD700',
      padding: 15,
      alignItems: 'center',
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    headerText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#000',
    },
    contentArea: {
      flex: 1,
      padding: 15,
    },
    contentScroll: {
      paddingBottom: 20,
    },
    contentTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#FFD700',
      marginBottom: 20,
      textAlign: 'center',
    },
    contentText: {
      fontSize: 16,
      color: '#ccc',
      lineHeight: 24,
      textAlign: 'justify',
    },
    songItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#3a3a3a',
      borderRadius: 10,
      padding: 10,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.23,
      shadowRadius: 2.62,
      elevation: 4,
    },
    songCover: {
      width: 60,
      height: 60,
      borderRadius: 5,
      marginRight: 15,
    },
    songTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#fff',
    },
    songArtist: {
      fontSize: 14,
      color: '#bbb',
    },
    tracksPreview: {
      marginTop: 5,
    },
    trackPreviewText: {
      fontSize: 12,
      color: '#ddd',
    },
    galleryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-around',
    },
    galleryImage: {
      width: 150,
      height: 150,
      borderRadius: 10,
      marginBottom: 5,
      resizeMode: 'cover',
      borderColor: '#FFD700',
      borderWidth: 1,
    },
    galleryImageText: {
      color: '#fff',
      fontSize: 14,
      textAlign: 'center',
      marginBottom: 15,
    },
    menuBar: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      backgroundColor: '#FFD700',
      paddingVertical: 10,
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.29,
      shadowRadius: 4.65,
    },
    menuItem: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
      marginHorizontal: 5,
      borderRadius: 8,
    },
    activeMenuItem: {
      backgroundColor: '#FFA500',
    },
    menuText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
    },
    activeMenuText: {
      color: '#FFF',
    },
  }),

  estilosDetalhesAlbum: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#2a2a2a',
    },
    backButton: {
      padding: 15,
      backgroundColor: '#FFD700',
      alignSelf: 'flex-start',
      borderRadius: 8,
      margin: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    backButtonText: {
      color: '#000',
      fontSize: 16,
      fontWeight: 'bold',
    },
    scrollContent: {
      padding: 20,
      alignItems: 'center',
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#FFD700',
      marginBottom: 10,
      textAlign: 'center',
    },
    year: {
      fontSize: 18,
      color: '#bbb',
      marginBottom: 20,
    },
    albumCover: {
      width: 250,
      height: 250,
      borderRadius: 15,
      marginBottom: 25,
      borderColor: '#FFD700',
      borderWidth: 2,
      resizeMode: 'cover',
    },
    description: {
      fontSize: 16,
      color: '#ccc',
      lineHeight: 24,
      textAlign: 'justify',
      marginBottom: 20,
    },
    tracksContainer: {
      width: '100%',
      padding: 15,
      backgroundColor: '#3a3a3a',
      borderRadius: 10,
      marginTop: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.23,
      shadowRadius: 2.62,
      elevation: 4,
    },
    tracksTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFD700',
      marginBottom: 10,
      textAlign: 'center',
    },
    trackItem: {
      fontSize: 16,
      color: '#ccc',
      marginBottom: 5,
      textAlign: 'left',
    },
    trackItemHighlighted: {
      fontWeight: 'bold',
      color: '#FFD700',
      fontSize: 17,
    },
    highlightedTrackContainer: {
      width: '100%',
      padding: 15,
      backgroundColor: '#4a4a4a',
      borderRadius: 10,
      marginTop: 10,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.28,
      shadowRadius: 3.84,
      elevation: 5,
      alignItems: 'center',
    },
    highlightedTrackTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFF',
      marginBottom: 8,
    },
    highlightedTrackItem: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFD700',
      marginBottom: 5,
      textAlign: 'center',
    },
    highlightedTrackDescriptionText: {
      fontSize: 14,
      color: '#ddd',
      lineHeight: 20,
      textAlign: 'justify',
      paddingHorizontal: 10,
    },
    errorText: {
      color: 'red',
      textAlign: 'center',
      marginTop: 50,
      fontSize: 18,
    },
  }),
};

export default estilos;
